apiVersion: v1
kind: Secret
metadata:
  name: crm-postgresql
  namespace: default
  labels:
    app: crm-postgresql
type: Opaque
data:
  postgresql-password: YmtpNWhnOTc=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-postgresql
  template:
    metadata:
      labels:
        app: crm-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:11.2
          env:
            - name: POSTGRES_USER
              value: crm
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crm-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/
---
apiVersion: v1
kind: Service
metadata:
  name: crm-postgresql
  namespace: default
spec:
  selector:
    app: crm-postgresql
  ports:
    - port: 5432
